name: Autograding Workflow

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: (github.event_name != 'push' || github.event.head_commit.message != 'Initial commit')

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install
        timeout-minutes: 1

      - uses: education/autograding@v1
        timeout-minutes: 1
